/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: m4ty1k4 (https://sketchfab.com/m4ty1k4)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sci-fi-lowpoly-dashboard-c43dfbc4d1b84a55b8d3581493965c69
Title: Sci-fi lowpoly Dashboard
*/

// import { useGLTF } from "@react-three/drei";

// const HeroImage = (props) => {
//   const { nodes, materials } = useGLTF("/models/sci-fi_lowpoly_dashboard.glb");
//   return (
//     <group {...props} dispose={null}>
// <group
//   position={[0, -10, -0.093]}
//   rotation={[-Math.PI / 2, 0, 0]}
//   scale={27}
// >
//         <group rotation={[Math.PI / 2, 0, 0]}>
//           <group scale={0.01}>
//             <mesh
//               castShadow
//               receiveShadow
//               geometry={nodes.Sidetables_low_Table_TX_0.geometry}
//               material={materials.Table_TX}
//               position={[-5.322, 0, -9.654]}
//               rotation={[0, Math.PI / 4, 0]}
//             />
//             <mesh
//               castShadow
//               receiveShadow
//               geometry={nodes.Midtables_low_Table_TX_0.geometry}
//               material={materials.Table_TX}
//             />
//             <mesh
//               castShadow
//               receiveShadow
//               geometry={nodes.Emissives_low_Emissive_TX_0.geometry}
//               material={materials.Emissive_TX}
//             />
//           </group>
//         </group>
//       </group>
//     </group>
//   );
// };

// useGLTF.preload("/models/sci-fi_lowpoly_dashboard.glb");

// export default HeroImage;
/////////////////////////////////
////////////////////////////////
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Argemlach (https://sketchfab.com/Argemlach)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/xyz-homework-detailing-retro-computer-87844a09b31642a781123bca89e81c3a
Title: XYZ Homework: Detailing. Retro Computer
*/

// import { useGLTF } from "@react-three/drei";

// const HeroImage = (props) => {
//   const { nodes, materials } = useGLTF(
//     "/models/xyz_homework_detailing._retro_computer.glb"
//   );
//   return (
//     <group {...props} dispose={null}>
//       <group rotation={[-Math.PI / 2, 0, 0]}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_2.geometry}
//           material={materials.GlassGreenPP}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_3.geometry}
//           material={materials.GlassRed}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_4.geometry}
//           material={materials.GlassRedPP}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_5.geometry}
//           material={materials.MonitorRed}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_6.geometry}
//           material={materials.PlasticYellow}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_7.geometry}
//           material={materials.PlastickPP}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_8.geometry}
//           material={materials.TableGradient}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_9.geometry}
//           material={materials.TableUp}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_10.geometry}
//           material={materials.Emissiom}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_11.geometry}
//           material={materials.GreenCenter}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_12.geometry}
//           material={materials.GreenDark}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_13.geometry}
//           material={materials.GreenDark}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_14.geometry}
//           material={materials.GreenPlasticPP}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_15.geometry}
//           material={materials.Laser}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_16.geometry}
//           material={materials.LaserPP}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_17.geometry}
//           material={materials.Mark}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_18.geometry}
//           material={materials.MonitorGreen}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_19.geometry}
//           material={materials.MonitorYellow}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_20.geometry}
//           material={materials.PlastickDark}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_21.geometry}
//           material={materials.PlastickLight}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_22.geometry}
//           material={materials.PlastickMetallLight}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_23.geometry}
//           material={materials.PlastikRed}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_24.geometry}
//           material={materials.PlastikWhite}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_25.geometry}
//           material={materials.Purple}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_26.geometry}
//           material={materials.Stripes}
//         />
//       </group>
//     </group>
//   );
// };

// useGLTF.preload("/models/xyz_homework_detailing._retro_computer.glb");

// export default HeroImage;

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: djones_CQU (https://sketchfab.com/djones_CQU)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/the-night-owls-desk-1645fa150e5243b29fc9394312c348c3
Title: The Night Owl's Desk
*/

import { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

const HeroImage = (props) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/the_night_owls_desk.glb"
  );
  // eslint-disable-next-line no-unused-vars
  const { actions } = useAnimations(animations, group);

  console.log(materials);

  const goldLampMaterial = materials.gold_lamp;

  goldLampMaterial.color.setRGB(
    goldLampMaterial.color.r,
    goldLampMaterial.color.g,
    0.555555555
  );

  const keyboardMaterial = materials.gold_cpu;

  keyboardMaterial.color.setRGB(255, 255, 255);

  const whiteMug = materials.base_mug;

  whiteMug.color.setRGB(
    0.8,

    0.7644831881845304,

    0.8193024440314856
  );

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          position={[0, -5, 0]}
          rotation={[1.75, 3.14, 1.6]}
          scale={0.2}
        >
          <group
            name="45b254b5d2ae41faa5304c013dfba576fbx"
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group name="Object_2">
              <group name="RootNode">
                <group
                  name="calculator"
                  position={[14.688, -0.289, 23.299]}
                  rotation={[0, 0.563, 0]}
                  scale={[1.346, 0.573, 1.313]}
                >
                  <mesh
                    name="calculator_buttons_calc_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.calculator_buttons_calc_0.geometry}
                    material={materials.buttons_calc}
                  />
                  <mesh
                    name="calculator_base_calc_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.calculator_base_calc_0.geometry}
                    material={materials.base_calc}
                  />
                  <mesh
                    name="calculator_display_calc_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.calculator_display_calc_0.geometry}
                    material={materials.display_calc}
                  />
                  <group name="transform40" position={[0, 0.774, 0]} />
                </group>
                <group
                  name="computer"
                  position={[-16.098, 0.302, 1.209]}
                  scale={1.91}
                >
                  <mesh
                    name="computer_gold_cpu_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.computer_gold_cpu_0.geometry}
                    material={keyboardMaterial}
                  />
                  <mesh
                    name="computer_base_cpu_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.computer_base_cpu_0.geometry}
                    material={materials.base_cpu}
                  />
                  <mesh
                    name="computer_screen_cpu_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.computer_screen_cpu_0.geometry}
                    material={materials.screen_cpu}
                  />
                </group>
                <group
                  name="lamp"
                  position={[-12.292, 1.107, 33.01]}
                  rotation={[0, 0.631, 0]}
                  scale={1.383}
                >
                  <mesh
                    name="lamp_gold_lamp_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.lamp_gold_lamp_0.geometry}
                    material={goldLampMaterial}
                  />
                  <mesh
                    name="lamp_dark_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.lamp_dark_0.geometry}
                    material={materials.dark}
                  />
                  <mesh
                    name="lamp_metal_lamp_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.lamp_metal_lamp_0.geometry}
                    material={materials.metal_lamp}
                  />
                  <mesh
                    name="lamp_bulb_lamp_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.lamp_bulb_lamp_0.geometry}
                    material={materials.bulb_lamp}
                  />
                </group>
                <group
                  name="pSphere3"
                  position={[18.635, 0.696, 4.917]}
                  rotation={[-1.683, 0.477, 0.241]}
                >
                  <mesh
                    name="pSphere3_standardSurface4_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere3_standardSurface4_0.geometry}
                    material={materials.standardSurface4}
                  />
                  <mesh
                    name="pSphere3_chrome1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere3_chrome1_0.geometry}
                    material={materials.chrome1}
                  />
                  <mesh
                    name="pSphere3_pasted__chrome1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pSphere3_pasted__chrome1_0.geometry}
                    material={materials.pasted__chrome1}
                  />
                </group>
                <group
                  name="pCylinder5"
                  position={[6.458, -0.119, -26.27]}
                  rotation={[0, -0.756, 0]}
                  scale={2.003}
                >
                  <mesh
                    name="pCylinder5_base_mug_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder5_base_mug_0.geometry}
                    material={materials.base_mug}
                  />
                  <mesh
                    name="pCylinder5_Default_Material_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder5_Default_Material_0.geometry}
                    material={materials.Default_Material}
                  />
                  <mesh
                    name="pCylinder5_fluid_mug_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder5_fluid_mug_0.geometry}
                    material={materials.fluid_mug}
                  />
                  <mesh
                    name="pCylinder5_coaster_mug_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCylinder5_coaster_mug_0.geometry}
                    material={materials.coaster_mug}
                  />
                </group>
                <group name="pCube1" scale={[12.975, 1, 8.224]}>
                  <group name="transform6" />
                </group>
                <group
                  name="pTorus1"
                  position={[0, 6.221, 3]}
                  rotation={[Math.PI / 2, 0.196, 0]}
                >
                  <group name="transform1" />
                </group>
                <group
                  name="pTorus2"
                  position={[0, 6.221, -3]}
                  rotation={[Math.PI / 2, 0.196, 0]}
                >
                  <group name="transform2" />
                </group>
                <group name="pTorus3" scale={[1.134, 1, 1]}>
                  <group name="transform5" />
                </group>
                <group name="pSphere1" position={[0, 2.842, 0]}>
                  <group name="transform4" />
                </group>
                <group
                  name="pCylinder1"
                  position={[0, 3.782, 0]}
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={[0.057, 5.419, 0.057]}
                >
                  <group name="transform3" />
                </group>
                <group
                  name="bend1Handle"
                  position={[0.014, 3.782, 0]}
                  rotation={[-Math.PI / 2, -Math.PI / 2, 0]}
                  scale={8.16}
                />
                <group name="bend1Handle1">
                  <group name="transform9" />
                </group>
                <group name="bend1Handle2" position={[1.986, 0, 0]}>
                  <group name="transform7" />
                </group>
                <group name="bend1Handle3" position={[3.986, 0, 0]}>
                  <group name="transform12" />
                </group>
                <group name="bend1Handle4" position={[-2.014, 0, 0]}>
                  <group name="transform8" />
                </group>
                <group name="bend1Handle5" position={[-4.014, 0, 0]}>
                  <group name="transform11" />
                </group>
                <group name="pCube2">
                  <group name="transform10" />
                </group>
                <group name="pCube3">
                  <group name="transform13" />
                </group>
                <group
                  name="pCube4"
                  position={[-15.35, 0.574, -28.198]}
                  rotation={[0, 1.056, 0]}
                  scale={1.648}
                >
                  <mesh
                    name="pCube4_ball_rose3_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube4_ball_rose3_0.geometry}
                    material={materials.ball_rose3}
                  />
                  <mesh
                    name="pCube4_ball_pink1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube4_ball_pink1_0.geometry}
                    material={materials.ball_pink1}
                  />
                  <mesh
                    name="pCube4_metal4_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube4_metal4_0.geometry}
                    material={materials.metal4}
                  />
                  <mesh
                    name="pCube4_ball_purple1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube4_ball_purple1_0.geometry}
                    material={materials.ball_purple1}
                  />
                  <mesh
                    name="pCube4_ball_violet1_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube4_ball_violet1_0.geometry}
                    material={materials.ball_violet1}
                  />
                  <mesh
                    name="pCube4_ball_blue3_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube4_ball_blue3_0.geometry}
                    material={materials.ball_blue3}
                  />
                  <mesh
                    name="pCube4_base_0"
                    castShadow
                    receiveShadow
                    geometry={nodes.pCube4_base_0.geometry}
                    material={materials.base}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
};

useGLTF.preload("/models/the_night_owls_desk.glb");

export default HeroImage;
